# This file was generated by GoReleaser. DO NOT EDIT.
cask "jirawk" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "d299237f9de50a38876eb9ccc51d8eb022a0b1e7d9755b1d2a74e308dc0b703a"
      url "https://github.com/figarocorso/jirawk/releases/download/v#{version}/jirawk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0775a6bec6fda0cd7a003a007df8a1f567491acfb0eb7d4c57e4ba98192a991"
      url "https://github.com/figarocorso/jirawk/releases/download/v#{version}/jirawk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9d67cdccd261d9f2db2b7e7b3ff07e4166144b7fd35f791c7d1868af167fb3c1"
      url "https://github.com/figarocorso/jirawk/releases/download/v#{version}/jirawk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e02a13653ab304c175a28fd36ba3efa2d8c82b396e1d1f3e5e72faec80b2d5cb"
      url "https://github.com/figarocorso/jirawk/releases/download/v#{version}/jirawk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jirawk"
  desc "🦅 Keep watch over your in-progress and recently-closed Jira issues from the terminal."
  homepage "https://github.com/figarocorso/jirawk"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "jira-cli",
    ]

  binary "jirawk"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jirawk"]
    end
  end

  # No zap stanza required

end
