# This file was generated by GoReleaser. DO NOT EDIT.
cask "jirawk" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f244cd0fd29e3831d124e76ca9594c493dbc2db8a1632202d374e5e7484fb3af"
      url "https://github.com/figarocorso/jirawk/releases/download/v#{version}/jirawk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "25defdee980ceee158b73664e9cb85fc2662be2a9cdcc7d8bb130806aa246c06"
      url "https://github.com/figarocorso/jirawk/releases/download/v#{version}/jirawk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "557e73020850b5fb871bd33b7d6002d6a365577cbf945ddd715017f9ed59f891"
      url "https://github.com/figarocorso/jirawk/releases/download/v#{version}/jirawk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f70cf62102ddf6034d7487c99c95fcdbbeafddf363da949ce6d3f05817c6dd9"
      url "https://github.com/figarocorso/jirawk/releases/download/v#{version}/jirawk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jirawk"
  desc "🦅 Keep watch over your in-progress and recently-closed Jira issues from the terminal."
  homepage "https://github.com/figarocorso/jirawk"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "jira-cli",
    ]

  binary "jirawk"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jirawk"]
    end
  end

  # No zap stanza required

end
