# This file was generated by GoReleaser. DO NOT EDIT.
cask "jirawk" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "25359036f35dd31ea4b85c59f0a4400642749d84f975b603d9e67a321a5af093"
      url "https://github.com/figarocorso/jirawk/releases/download/v#{version}/jirawk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28cf2ef73a3ce0d16bcb3ba64346ab946c4b61b515f2380fce38e0ce474c30cc"
      url "https://github.com/figarocorso/jirawk/releases/download/v#{version}/jirawk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8789150d095f6de16a08e9a9c7ea7e97d2734432875ea83f22ba8515c1c5977b"
      url "https://github.com/figarocorso/jirawk/releases/download/v#{version}/jirawk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bfd07fad46d49707a94699e3a8d678557ef10fd904ca4526636f4715aff0daf0"
      url "https://github.com/figarocorso/jirawk/releases/download/v#{version}/jirawk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jirawk"
  desc "🦅 Keep watch over your in-progress and recently-closed Jira issues from the terminal."
  homepage "https://github.com/figarocorso/jirawk"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "jira-cli",
    ]

  binary "jirawk"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jirawk"]
    end
  end

  # No zap stanza required

end
