# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jirawk < Formula
  desc "🦅 Keep watch over your in-progress and recently-closed Jira issues from the terminal."
  homepage "https://github.com/figarocorso/jirawk"
  version "0.1.0"
  license "Apache-2.0"

  depends_on "ankitpokhrel/jira-cli/jira-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/figarocorso/jirawk/releases/download/v0.1.0/jirawk_0.1.0_darwin_amd64.tar.gz"
      sha256 "0dcfc8ba518a185f07c41576449badc8b3fd5cebbafc9963fb313a44853b35a3"

      define_method(:install) do
        bin.install "jirawk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/figarocorso/jirawk/releases/download/v0.1.0/jirawk_0.1.0_darwin_arm64.tar.gz"
      sha256 "97d2750e62dec3bc987cbacadafcfc8adb5d79bdf554108dfbb0a020d72ea925"

      define_method(:install) do
        bin.install "jirawk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/figarocorso/jirawk/releases/download/v0.1.0/jirawk_0.1.0_linux_amd64.tar.gz"
      sha256 "809c8334df0ac99e1acfe8de6993306ceb544faa810386acf9653b6249b27a69"
      define_method(:install) do
        bin.install "jirawk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/figarocorso/jirawk/releases/download/v0.1.0/jirawk_0.1.0_linux_arm64.tar.gz"
      sha256 "718a2ae766dd6fcb4d4ecac2ba1187d7a01aa182598f38fdbee6ee5c88b641f2"
      define_method(:install) do
        bin.install "jirawk"
      end
    end
  end

  test do
    system "#{bin}/jirawk", "--help"
  end
end
