# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jirawk < Formula
  desc "🦅 Keep watch over your in-progress and recently-closed Jira issues from the terminal."
  homepage "https://github.com/figarocorso/jirawk"
  version "0.1.1"
  license "Apache-2.0"

  depends_on "jira-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/figarocorso/jirawk/releases/download/v0.1.1/jirawk_0.1.1_darwin_amd64.tar.gz"
      sha256 "616d3c6454f6585d14dee36c13059599bb77a3e5f187ef923e62f9b844f1d7c2"

      define_method(:install) do
        bin.install "jirawk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/figarocorso/jirawk/releases/download/v0.1.1/jirawk_0.1.1_darwin_arm64.tar.gz"
      sha256 "908717dffed7856a92ab40b427e6ce964de7b5d27248a85ec807e0e3303cd3a9"

      define_method(:install) do
        bin.install "jirawk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/figarocorso/jirawk/releases/download/v0.1.1/jirawk_0.1.1_linux_amd64.tar.gz"
      sha256 "a226a022f427cc15f87131dab12d31b97b7c73769ce2f2464e347f7083e1fc34"
      define_method(:install) do
        bin.install "jirawk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/figarocorso/jirawk/releases/download/v0.1.1/jirawk_0.1.1_linux_arm64.tar.gz"
      sha256 "b03df32330d867a6896fe28631ef3745356930bb113f116093b3b0d8323c7f70"
      define_method(:install) do
        bin.install "jirawk"
      end
    end
  end

  test do
    system "#{bin}/jirawk", "--help"
  end
end
