# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prowl < Formula
  desc "🦉 Keep watch over your GitHub Pull Requests from the terminal."
  homepage "https://github.com/figarocorso/prowl"
  version "0.4.0"
  license "Apache-2.0"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/figarocorso/prowl/releases/download/v0.4.0/prowl_0.4.0_darwin_amd64.tar.gz"
      sha256 "44a7442a097cfffbcf59af333d481d443d612cb0395879f48c69ff8964f34949"

      define_method(:install) do
        bin.install "prowl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/figarocorso/prowl/releases/download/v0.4.0/prowl_0.4.0_darwin_arm64.tar.gz"
      sha256 "812ed102a37b67bdc9fd79c1d403ebdb3f6b07d61a450e81d344ba2e74a815fb"

      define_method(:install) do
        bin.install "prowl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/figarocorso/prowl/releases/download/v0.4.0/prowl_0.4.0_linux_amd64.tar.gz"
      sha256 "8907b8cc236a888e284c36fe877a1c4eae6b1dccfba361bf870249a0a558de6d"
      define_method(:install) do
        bin.install "prowl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/figarocorso/prowl/releases/download/v0.4.0/prowl_0.4.0_linux_arm64.tar.gz"
      sha256 "9967e5a3d6d97b78d362604104787888c3d1cbcd7fd66579766ec4781cb2b8f8"
      define_method(:install) do
        bin.install "prowl"
      end
    end
  end

  test do
    system "#{bin}/prowl", "--help"
  end
end
