# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prowl < Formula
  desc "🦉 Keep watch over your GitHub Pull Requests from the terminal."
  homepage "https://github.com/figarocorso/prowl"
  version "0.5.3"
  license "Apache-2.0"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/figarocorso/prowl/releases/download/v0.5.3/prowl_0.5.3_darwin_amd64.tar.gz"
      sha256 "4806f1434f2e2b416ee98b9a50aafc208e5a46b00e14d309181b12ca525397df"

      define_method(:install) do
        bin.install "prowl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/figarocorso/prowl/releases/download/v0.5.3/prowl_0.5.3_darwin_arm64.tar.gz"
      sha256 "e352b30c0e27a8339f69dfd7d3aefefff44d6c0dbb392e4642062ed39af3467a"

      define_method(:install) do
        bin.install "prowl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/figarocorso/prowl/releases/download/v0.5.3/prowl_0.5.3_linux_amd64.tar.gz"
      sha256 "f7247f3100ceb3ffab464ff78e8ae305a0ab3eb88fb58056de1481fe590cd252"
      define_method(:install) do
        bin.install "prowl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/figarocorso/prowl/releases/download/v0.5.3/prowl_0.5.3_linux_arm64.tar.gz"
      sha256 "97517440ce0dc681faa8e7aa21c7a0a98d959698ee61c9dcc5287fac90a8c249"
      define_method(:install) do
        bin.install "prowl"
      end
    end
  end

  test do
    system "#{bin}/prowl", "--help"
  end
end
